# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

well_commerce_layered_navigation:
    filters:
        priceFrom:
            type: integer
            condition: WellCommerce\Component\DataSet\Conditions\Condition\Gte
            enabled: true
            column: finalPrice
        priceTo:
            type: integer
            condition: WellCommerce\Component\DataSet\Conditions\Condition\Lte
            enabled: true
            column: finalPrice
        attributes:
            type: array
            condition: WellCommerce\Component\DataSet\Conditions\Condition\In
            enabled: true
            column: variantOption
        producers:
            type: array
            condition: WellCommerce\Component\DataSet\Conditions\Condition\In
            enabled: true
            column: producerId
        categories:
            type: array
            condition: WellCommerce\Component\DataSet\Conditions\Condition\In
            enabled: true
            column: filteredCategory
