# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

front.layered_navigation.filter:
    path: /filter
    defaults:
        _controller: 'layered_navigation.controller.front:filterAction'
    options:
        expose: true
